### ISSUE TITLE
Small Bugs And Missing Textures - Redstone Dust

### ISSUE THREAD

**Issue by ImTheCoreOfMc** [NoobTaco/John_Smith_Legacy_JSC-Bedrock#2]
![screenshot_2017-07-06-03-29-51](https://user-images.githubusercontent.com/21209395/27902509-a53bc2b6-61fb-11e7-9d04-aba02a67ebb4.png)
 found a bug or missing texture, the Redstone is is just two little red dots, i don't know if that is supposed to be that way @NoobTaco

**Comment by NoobTaco** [comment]
Created a second bug for the Evoker. Will investigate.

**Comment by ImTheCoreOfMc** [comment]
If i find anymore, I'll definitely let you know
